server:
  # 端口配置
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
    tomcat:
      # tomcat的URI编码
      uri-encoding: UTF-8
      # tomcat最大线程数，默认为200
      max-threads: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare-threads: 30

# spring相关配置
spring:
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wikidev?characterEncoding=UTF8&useUnicode=true&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: wikidev
    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# 日志相关配置
logging:
  # 日志级别
  level:
    com.avalon.wiki.mapper: debug

# mybatis相关配置
mybatis:
  # mapper配置文件路径
  mapper-locations: classpath:/mapper/**/*.xml
  # 实体类包路径
  type-aliases-package: com.avalon.wiki.domain

  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    # 打印sql语句
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 线程池配置
threadPool:
  # 异步线程池
  asyncThread:
    threadNamePrefix: 'asyncExecutor-'
    corePoolSize: 10
    maxPoolSize: 100
    keepAliveTime: 10
    queueCapacity: 200
    awaitTerminationSeconds: 60
    waitForTasksToCompleteOnShutdown: true

  # 定时任务线程池
  taskThread:
    threadNamePrefix: 'taskExecutor-'
    poolSize: 5
    awaitTerminationSeconds: 60
    waitForTasksToCompleteOnShutdown: true
